const mockOrders = [
    {
      "Timestamp": "11/04/2025 11:14:23",
      "Party unqiue ID": "EXP PUI 1",
      "Order ID": "EXP OI 1",
      "Party Name": "Abc store",
      "Contact No": "9020393020",
      "Country": "dubai",
      "Brand Name": "excel",
      "Quantity": 200,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "Pending",
      "Status (Packing of goods)": "Pending",
      "Status (Dispatch to port)": "",
      "Status (Receiving of goods at port)": "",
      "Status (Vessel Dispatch)": "",
      "Status (Goods received at party's port)": "",
    },
    {
      "Timestamp": "11/04/2025 11:14:23",
      "Party unqiue ID": "EXP PUI 1",
      "Order ID": "EXP OI 101",
      "Party Name": "Abc store",
      "Contact No": "9020393020",
      "Country": "dubai",
      "Brand Name": "excel",
      "Quantity": 200,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "",
      "Status (Packing of goods)": "",
      "Status (Dispatch to port)": "",
      "Status (Receiving of goods at port)": "",
      "Status (Vessel Dispatch)": "",
      "Status (Goods received at party's port)": "",
    },
    {
      "Timestamp": "12/04/2025 02:12:23",
      "Party unqiue ID": "EXP PUI 2",
      "Order ID": "EXP OI 2",
      "Party Name": "Mohit store",
      "Contact No": "9339230293",
      "Country": "Malaysia",
      "Brand Name": "super",
      "Quantity": 230,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "Done",
      "Status (Packing of goods)": "Done",
      "Status (Dispatch to port)": "Done",
      "Status (Receiving of goods at port)": "Pending",
      "Status (Vessel Dispatch)": "",
      "Status (Goods received at party's port)": "",
    },
    {
      "Timestamp": "11/04/2025 13:00:23",
      "Party unqiue ID": "EXP PUI 3",
      "Order ID": "EXP OI 3",
      "Party Name": "Raju store",
      "Contact No": "9002930293",
      "Country": "Iraq",
      "Brand Name": "wattan se",
      "Quantity": 120,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "pending",
      "Status (Packing of goods)": "",
      "Status (Dispatch to port)": "",
      "Status (Receiving of goods at port)": "",
      "Status (Vessel Dispatch)": "",
      "Status (Goods received at party's port)": "",
    },
    {
      "Timestamp": "11/04/2025 13:00:23",
      "Party unqiue ID": "EXP PUI 4",
      "Order ID": "EXP OI 4",
      "Party Name": "Rahul store",
      "Contact No": "9002930293",
      "Country": "Iraq",
      "Brand Name": "wattan se",
      "Quantity": 120,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "Done",
      "Status (Packing of goods)": "Done",
      "Status (Dispatch to port)": "pending",
      "Status (Receiving of goods at port)": "",
      "Status (Vessel Dispatch)": "",
      "Status (Goods received at party's port)": "",
    },
    {
      "Timestamp": "11/04/2025 13:00:23",
      "Party unqiue ID": "EXP PUI 5",
      "Order ID": "EXP OI 5",
      "Party Name": "Shivam store",
      "Contact No": "9002930293",
      "Country": "Iraq",
      "Brand Name": "wattan se",
      "Quantity": 120,
      "Status (Order confirmation)": "Done",
      "Status (Packing Material Received)": "Done",
      "Status (Packing of goods)": "Done",
      "Status (Dispatch to port)": "Done",
      "Status (Receiving of goods at port)": "Done",
      "Status (Vessel Dispatch)": "Done",
      "Status (Goods received at party's port)": "Done",
    },
  ];
  
  export default mockOrders;
  